### ISSUE TITLE
Dual license GPLv3 with a BSD-like license

### ISSUE THREAD

**Issue by o-kotb** [Windscribe/iOS-App#1]
With the current license being the only option for the iOS app, I think it's impossible for anyone to use it for its intended purpose because of the known conflict between App Store's ToS and GPL. And because iOS doesn't support alternative app stores like Android and that the App Store is the only way to realistically distribute apps for iOS, it's effectively impossible for anyone to make use of the open source code except for, of course, the copyright holders. Essentially, it's now proprietary source available for iOS.

Also, I'm not sure if this project accepts code contributions, but you wouldn't be able to use those contributions on the App Store either if they're also only in GPL.

I propose to dual license the project with one of the widely used free and open source licenses like BSD 3, Apache 2, or Expat licenses. Or even use it exclusively.

**Comment by Ginder-Singh** [comment]
Windscribe iOS app uses OpenVPN(Most VPN apps on app store do) which is GPLv2 so we have no choice then to stay on GPL licence.
