### ISSUE TITLE
Please make a TV OS app

### ISSUE THREAD

**Issue by BraveDevelopment** [Windscribe/iOS-App#2]
It would be amazing if someone who knew how to do it would make an app for the Apple TV out of this. There are no good VPN apps for TV OS and to be able to watch your favorite tv shows from other countries would be awesome!

**Comment by Ginder-Singh** [comment]
Yes we are already working on TV app.

**Comment by BraveDevelopment** [comment]
> Yes we are already working on TV app.

Amazing. Can you share a link to the repository?

**Comment by Ginder-Singh** [comment]
We will use same repository. Currently we are planning & porting all dependencies to support tvOS. Next step is to add UI for it. We will update repo once we have something in working state.
