### ISSUE TITLE
Crash on iOS 12.5.7

### ISSUE THREAD

**Issue by b0gdanw** [Windscribe/iOS-App#3]
App versions affected: 3.8.1 & 3.8.2
App versions not affected: 3.7.9 and below

`Process:             Windscribe [234]
Path:                /private/var/containers/Bundle/Application/903A0BBA-AEBF-480A-B3D7-A22FB126908F/Windscribe.app/Windscribe
Identifier:          com.windscribe
Version:             5 (3.8.2)
AppStoreTools:       15F31e
AppVariant:          1:iPhone7,2:12.2
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.windscribe [352]

OS Version:          iPhone OS 12.5.7 (16H81)

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Symbol not found: ___darwin_check_fd_set_overflow | Referenced from: /private/var/containers/Bundle/Application/903A0BBA-AEBF-480A-B3D7-A22FB126908F/Windscribe.app/Frameworks/wsnet.framework/wsnet | Expected in: dyld shared cache | in /private/var/containers/Bundle/Application/903A0BBA-AEBF-480A-B3D7-A22FB126908F/Windscribe.app/Frameworks/wsnet.framework/wsnet
Triggered by Thread:  0`

**Comment by Ginder-Singh** [comment]
I am unable to install old simulator such as 12.2 . I have ordered an old iphone 5s which is locked to 12.5 .  It should be here sometime this week. I will update this issue when I am able to reproduce and have some solution for it.

**Comment by Ginder-Singh** [comment]
@b0gdanw can you update to 3.8.3 from internal channel after joining
https://testflight.apple.com/join/SrbvfhT8

**Comment by Ginder-Singh** [comment]
Issue fixed in latest test flight build 3.8.3(15).
